### ISSUE TITLE
Unnecessary request for microphone and location always usage permissions

### ISSUE THREAD

**Issue by petersteinenberg** [austrianredcross/stopp-corona-ios#38]
According to the iOS Info.plist the app requests permissions for "Location Always Usage" and "Microphone Usage" (!). Both permissions are unnecessary and their presence undermines the trustworthiness of the app. These permissions should be removed.

**Comment by uliluckas** [comment]
Hi @petersteinenberg 
why do you claim these permissions are unnecessary?
Background handshake works via BLE scanning.
Foreground handshake via near ultrasound.

regards,
Uli

**Comment by bastianh** [comment]
to be more precise the app never asks for location permissions.
The info.plist has to contain the the keys for location permissions because the google nearby library could use it ( so the functionality is in the app ), but we never request or use it.

as uli already said the manual handshake uses the microphone to listen to other apps already in manual handshake mode. if you don‘t do manual handshake the microphone permission is not requested. while the app uses the microphone there is a clear indicator that it is currently listening for other devices.

**Comment by petersteinenberg** [comment]
Both permissions are risky and prone to (later) misuse and should therefore be avoided. No other privacy conscious tracking app I'm aware of requests these kind of permissions. How would you explain to a regular user that this app needs the microphone? The only valid reason these days is when the user interacts by voice with the app and not the establishment of hidden ("near ultrasound") side channels. I'd still recommend to reconsider your broad usage of risky permissions even if they look legitimate to you.

**Comment by bastianh** [comment]
The usage of the microphone is explained when you start the manual handshake the first time. The usage is not required, you can decline it and still use only the automatic handshake of the app.
As already stated the location permission is never requested. The string in the info.plist is required by apple nevertheless. I'm pretty sure we will never request it in the future, the app is checked by many data protection agencies.
Thank you for your opinion.
